image_topic: /monocular/image_raw
mavros_altitude_topic: /mavros/local_position/odom
vis_infer: True

camera:
  resolution: [640, 480]
  angles: [155.0, 120.0]

density_estimator:
  path: './data/density_estimator.onnx'
  onnx_provider: cpu # tensorrt, cuda or cpu
  conf_thresh: 0.6

keypoints_detector:
  path: './data/keypoints_detector.onnx'
  onnx_provider: cpu # tensorrt, cuda or cpu
  conf_thresh: 0.3
  std_thresh: 1e-3

rotation_estimator:
  camera_matrix: [
    [1.00000000e+00, 0.00000000e+00, 320],
    [0.00000000e+00, 1.00000000e+00, 240],
    [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]
  ]
  dist_coeffs: [
    [ 0, 0,  0, 0, 0]
  ]
  target_real_model: [
    [0.0, 0.0, 0.0], #middle
    [0.0, -0.4, 0.0], #up
    [0.4, 0.4, 0.0], #right
    [-0.4, 0.4, 0.0], #left
  ]
