## parameter for uav_control

control:
  # cascade_pid: P for POS, PID for VEL
  # pid:         PID for POS
  # passivity:   PD+UDE+passivity for POS
  # ude:         PD+UDE for POS
  # ne:          PD+UDE+NE for POS
  # Eason_PID:   PID for POS & VEL
  controller_type : cascade_pid
  # 是否支持外部控制
  enable_external_control : true
  ## 起飞高度
  Takeoff_height : 1.5
  ## 降落速度
  Land_speed : 0.3
  ##　上锁高度
  Disarm_height : 0.2
  ## 定位源: 0 for MOCAP, 1 for T265, 2 for GAZEBO, 3 for FAKE_ODOM, 4 for GPS, 5 for RTK, 6 for UWB, 7 for VINS, 8 for OpticalFlow
  location_source : 2
  ## 最大安全速度
  maximum_safe_vel_xy : 0.2
  maximum_safe_vel_z : 0.5
  ## 最大vision/px4速度误差
  maximum_vel_error_for_vision : 100.0

##　地理围栏
geo_fence:
  x_min: -8.0
  x_max: 8.0
  y_min: -5.0
  y_max: 5.0
  z_min: -0.3
  z_max: 3.0
