yolo_model:
  config_file:
    name: yolov2-CUADC.cfg
  weight_file:
    name: yolov2-CUADC-1500.weights
  threshold:
    value: 0.5
  detection_classes:
    names:
      - cylinder_bucket
      - landing_pad
